RTIK/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace='main')),
    url(r'blog/', include('blog.urls', namespace='blog'))
]

blog/urls.py
from django.conf.urls import url

from .views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^tambah/$', Tambah.as_view(), name='tambah'),
    url(r'^(?P<pk>[0-9]+)/$', Detail.as_view(), name='detail'),
]

main/urls.py
from django.conf.urls import url
from .views import *
app_name = 'main'


urlpatterns = [
    url(r'^$', Home.as_view(), name='home')
]

blog/models.py
from django.db import models


# Create your models here.
from django.shortcuts import redirect


class Blog(models.Model):
    judul = models.CharField(max_length=120)
    konten = models.TextField(max_length=1200)

    def get_absolute_url(self):
        return redirect('blog:index')

main/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, CreateView, DetailView
from .models import *
from django.views.generic.base import View


class Index(ListView):
    model = Blog
    template_name = 'blog/index.html'


class Tambah(CreateView):
    model = Blog
    fields = '__all__'
    template_name = 'blog/tambah.html'


class Detail(DetailView):
    model = Blog
    template_name = 'blog/singel.html'

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.


class Home(TemplateView):
    template_name = 'main/home.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}
    Judul
  {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

{#    <style media="screen">#}
{#      header, main, footer{#}
{#        padding-left: 300px;#}
{#      }#}
{#      @media only screen and(max-width : 992px) {#}
{#        header, main, footer{#}
{#          padding-left: 0;#}
{#        }#}
{#      }#}
{#    </style>#}


</head>
<body>
    <!-- Ini bagian navigasinya-->

    <div class="navbar-fixed" >
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo right"> RTIK Muda Karawang </a>
                <a href="#!" data-activates="slide-out" class="button-collapse show-on-medium-and-up"><i class="material-icons"> account_circle </i></a>
                <ul>
                    <li class="nav-content"> <a href="{% url 'main:home' %}"><i class="material-icons">home</i></a> </li>
                    <li class="nav-content"> <a href="{% url 'blog:index' %}"> Blog </a> </li>
                    <li class="nav-content"> <a href="#!"> Kegiatan </a> </li>
                    <li class="nav-content"> <a href="#!"> Galeri </a> </li>
                    <li class="nav-content"> <a href="#!"> Join Us! </a> </li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- akhir navigasi -->
    <ul class="side-nav" id="slide-out">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{% static 'img/cover.jpg' %}" alt="ini foto loh">
                </div>
                <a href="#!"> <img src="{% static 'img/Folder.jpg' %}" class="circle" alt="ini juga foto">  </a>
                <a href=""> <span class="white-text name"> nama </span> </a>
                <a href=""> <span class="white-text email"> email@someone.com </span> </a>
            </div>
        </li>
        <li> <div class="divider"></div> </li>
        <ul class="collapsible">
          <li> <a href="{% url 'blog:index' %}" class="collapsible-header wave">Blog</a> </li>
        </ul>
        <li>
            <!-- Tentang blog atau artikel -->
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header"> Artikel <i class="material-icons right">arrow_drop_down</i> </a>
                    <div class="collapsible-body">
                        <ul>
                            <li> <a href="{% url 'blog:tambah' %}"> Buat Artikel <i class="material-icons right">add</i> </a></li>
{#                            <li> <a href="#!"> Artikel Baru <i class="material-icons right">min</i> </a> </li>#}
{#                            <li> <a href="#!"> Artikel Saya <i class="material-icons right">arrow_right</i> </a> </li>#}
                        </ul>
                    </div>
                </li>
            </ul>
        </li>

        <!-- tentang aktivitas kerelawanan -->
{#        <li>#}
{#            <ul class="collapsible collapsibe-accordion">#}
{#                <li>#}
{#                    <a class="collapsible-header"> Kerelawanan <i class="material-icons right">arrow_drop_down </i> </a>#}
{#                    <div class="collapsible-body">#}
{#                        <ul>#}
{#                            <li class="disable"> <a href="#!"> Kegiatan </a> </li>#}
{#                            <li class="disable"> <a href="#!"> Peringkat </a> </li>#}
{#                            <li class="disable"> <a href="#!"> Level Saya </a> </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </li>#}
{#            </ul>#}
{#        </li>#}
        <!-- akhir kerelwanan -->
{#        <li>#}
{#            <a href="#" class="subheader">  UI</a>#}
{#        </li>#}
    </ul>
    <!-- user informations -->

    <!-- end user informations -->
{#    <a href="#!" data-activates="slide-out" class="button-collapse show-on-large btn-floating fixed-action-btn"><i class="material-icons"> menu </i></a>#}
        {% block content %}
            <p> Isi atuh</p>
        {% endblock %}

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Relawan TIK Muda Karawang</h5>
                    <p class="grey-text text-lighten-4"> <i>Relawan Teknologi Informasi dan Komunikasi Muda Karawang</i> adalah komunitas kepemanduan yang berusaha mewujudkan Smart City di kota Karawang
                        Kegiatan yang kami lakukan meliputi literasi digital, penyuluhan penggunaan internet baik, dan pelayanan TIK
                    </p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Relawan TIK Muda Karawang</h5>
                    <div class="row">
                        <div class="col s4">
                            Sekretariat
                        </div>
                        <div class="col s8">
                            Jl. H.R Ronggowaluyo, Telukjambe Timur, Karawang - Jawa Barat, 14325
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s4">
                            Telepon <span> <i class="material-icons">phone</i> </span>
                        </div>
                        <div class="col s8">
                            0241-981-3239
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s4">
                            <span> <i class="material-icons">email</i> </span>
                        </div>
                        <div class="col s8">
                            <a href="mailto:informasi@rtikmuda.karawang.org">informasi@rtikmuda.karawang.org</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s4">
                            Facebook
                        </div>
                        <div class="col s8">
                            <a href="https://www.facebook.com/relawantikkrw/"> Relawan TIK Muda Karawang </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2018 Dibuat dengan semangat pengabdian oleh RTIK Muda Karawang
            </div>
        </div>
    </footer>
    <!--Import jQuery before materialize.js-->
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="{% static 'materialize/jQuery/init.js' %}"></script>
</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock %}

{% block content %}

    <div class="container">
    {% if object_list %}
        {% for object in object_list %}
            <div class="row">
                <div class="col s12">
                    <div class="card z-depth-2 large">
                        <div class="card-image">
                          {% load static %}
                          <img src="{% static 'img/Folder.jpg' %}" alt="ini juga foto" class="activator waves-effect">
                          <span class="card-title activator">{{object.judul}}</span>

                        </div>
                        <div class="card-content">
                          {{object.konten}}
                          <button type="button" name="up">Up</button>
                          <button type="button" name="up">Down</button>
                        </div>
                        <div class="card-reveal">
                          <span class="card-title"> {{object.judul}} <i class="material-icons right">close</i> </span>
                          <p>{{object.konten}}</p>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1> Kosong </h1>
    {% endif %}


    </div>
{% endblock %}

templates/blog/singel.html
{% extends 'base.html' %}

{% block title %}
    {{ object.judul }}
{% endblock %}

{% block content %}
    <h1> {{ object.judul }} </h1>
    <p> {{ object.konten }} </p>

{% endblock %}

templates/blog/tambah.html
{% extends 'base.html' %}

{% block title %}
    Tambah Post
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row z-depth-3" style="padding:10px">
        <form method="post" action="">
            {% csrf_token %}
            <div class="input-field">
              <label> {{form.judul.label}} </label>
              {{form.judul}}
              <p class="text-danger">{{form.judul.errors}}</p>
            </div>
            <div class="input-field">
              {% load widget_tweaks %}
              <label> {{form.konten.label}} </label>
              {{form.konten | add_class:"materialize-textarea"}}
            </div>
           <div class="col s6"><button type="reset" class="btn btn-block"> Reset </button> </div>
           <div class="col s6"><button type="submit" class="btn btn-block right"> Tambah </button> </div>
        </form>
    </div>
    </div>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
    RTIK Muda Karawang
{% endblock %}

{% block content %}
    <div class="row">
        <div class="slider">
            <ul class="slides">
                <li>
                    <img src="https://lorempixel.com/580/250/nature/1"> <!-- random image -->
                    <div class="caption center-align">
                        <h3>This is our big Tagline!</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                    </div>
                </li>
                <li>
                    <img src="https://lorempixel.com/580/250/nature/2"> <!-- random image -->
                    <div class="caption left-align">
                        <h3>Left Aligned Caption</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                    </div>
                </li>
                <li>
                    <img src="https://lorempixel.com/580/250/nature/3"> <!-- random image -->
                    <div class="caption right-align">
                        <h3>Right Aligned Caption</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                    </div>
                </li>
                <li>
                    <img src="https://lorempixel.com/580/250/nature/4"> <!-- random image -->
                    <div class="caption center-align">
                        <h3>This is our big Tagline!</h3>
                        <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col m4">
            <div class="card" style="background-color: #b1b2b3">
                <div class="card-title">
                    <h2> Literasi Digital </h2>
                </div>
                <div class="card-content">
                    <p>
                        Untuk mewujudkan SmartCity di Kota Karawang, tidak hanya perlu dikembangkan infrastruktur dan fasilitas saja. Dibutuhkan juga pengguna yang cerdas dalam menggunakan perangkat TIK
                    </p>
                </div>
            </div>
        </div>
        <div class="col m4">
            <div class="card" style="background-color: #e2e2e2">
                <div class="card-title">
                    <h2> Pengembangan Keahlian </h2>
                </div>
                <div class="card-content">
                    Perkembangan TIK tidak akan bermanfaat banyak bila tidak ditunjang dengan pengembangan keahlian manusia menggunakannya. It's Human and Robot VS Problem not Human VS Robot.
                </div>
            </div>
        </div>

        <div class="col m4">
            <div class="card" style="background-color: #7d6a4e">
                <div class="card-title">
                    <h2> Pelayanan TIK </h2>
                </div>
                <div class="card-content">
                    Pelayanan TIK ditujukan untuk pusat pengaduan dan bantuan masyarakat dalam mengunakan perangkat TIK
                </div>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}

templates/navbar.html
<div class="navbar-fixed">
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <a href="#" class="brand-logo right"> My SkripSweet </a>
                <a href="#!" data-activates="slide-out" class="button-collapse show-on-medium-and-up"><i class="material-icons"> menu </i></a>
            </div>
        </nav>
</div>

    <ul class="side-nav" id="slide-out">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="{% static 'img/853776-mist-wallpaper.jpg' %}" alt="ini foto loh">
                </div>
                <a href="#!"> <img src="{% static 'img/Folder.jpg' %}" class="circle" alt="ini juga foto">  </a>
                <a href=""> <span class="white-text name"> nama </span> </a>
                <a href=""> <span class="white-text email"> email@someone.com </span> </a>
            </div>
        </li>
        <li> <div class="divider"></div> </li>
        {% block menu %}
            Menunya tolong diisikan
        {% endblock %}
    </ul>